name: Go Test and Coverage

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - '**' 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.5

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests and generate coverage report
        run: |
          go test -v -coverprofile=coverage.out
          go tool cover -func=coverage.out

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out

      - name: Generate HTML coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage-report
          path: coverage.html
